<h1 align='center'><?= $this->escapeHtml($this->device->getModel()) ?></h1>
<div align='center'><h3><?= $this->escapeHtml($this->device->getCategory()) ?></h3></div>
<br><br>
<pre>
<br/>Производитель: <?= nl2br($this->device->getManufacturer()) ?>
<br/>Мощность:      <?= nl2br($this->device->getPower()) ?> Вт.
дата выпуска:  <?= nl2br($this->device->getRelease_date()) ?>г.
Свойства:      <?= nl2br($this->device->getProperty()) ?>
<br/>Описание:      <?= nl2br($this->device->getDescription()) ?>
</pre>
<br><br>
