<h2>Инструкции по платформам VAS SP</h2>

<div class="list-group">
<?php
	$arr = $posts->toArray();
	$categories = [];
	foreach ($arr as $post){ 
		$category = $post['category']; 
		if(! in_array($category, $categories)){
			array_push($categories, $category)?>
			<details>
				<summary><?= $post['category']?></summary>
				<?php	foreach ($arr as $post){  
							if($post['category'] == $category){ ?>
								<a href="<?= $this->url('home/detail', ['id' => $post['id']]) ?>">
									<?= $post['title'] ?><br/>
								</a>
							<?php	} ?>
				<?php } ?>
			</details>
		<?php } ?>
<?php } ?>
</div>
