<h1>Delete device</h1>

<p>Are you sure you want to delete the following device?</p>

<ul class="list-group">
    <li class="list-group-item"><?= $this->escapeHtml($this->device->getModel()) ?></li>
</ul>

<form action="<?php $this->url('admin/delete', [], true) ?>" method="post">
    <input type="hidden" name="id" value="<?= $this->escapeHtmlAttr($this->device->getId()) ?>" />
    <input class="btn btn-default" type="submit" name="confirm" value="Cancel" />
    <input class="btn btn-danger" type="submit" name="confirm" value="Delete" />
</form>