<?php
$form = $this->form;
$form->setAttribute('method', 'POST');
$fieldset = $form->get('device');

$model = $fieldset->get('model');
$model->setAttribute('class', 'form-control');
$model->setAttribute('placeholder', 'Model');

$category = $fieldset->get('category');
$category->setAttribute('class', 'form-control');
$category->setAttribute('placeholder', 'Category');

$manufacturer = $fieldset->get('manufacturer');
$manufacturer->setAttribute('class', 'form-control');
$manufacturer->setAttribute('placeholder', 'Manufacturer');

$power = $fieldset->get('power');
$power->setAttribute('class', 'form-control');
$power->setAttribute('placeholder', 'Power');

$release_date = $fieldset->get('release_date');
$release_date->setAttribute('class', 'form-control');
$release_date->setAttribute('placeholder', 'Date of release');

$property = $fieldset->get('property');
$property->setAttribute('class', 'form-control');
$property->setAttribute('placeholder', 'Property');

$description = $fieldset->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'Description');

$submit = $form->get('submit');
$submit->setValue($this->submitLabel);
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>
<head>
	<link rel="stylesheet" type="text/css" href="vf-style.css">
</head>
<fieldset>
<div class="form-group">
    <?= $this->formLabel($model) ?>
    <?= $this->formElement($model) ?>
    <?= $this->formElementErrors()->render($model, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($category) ?>
    <?= $this->formElement($category) ?>
    <?= $this->formElementErrors()->render($category, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($manufacturer) ?>
    <?= $this->formElement($manufacturer) ?>
    <?= $this->formElementErrors()->render($manufacturer, ['class' => 'help-block']) ?>
</div>
    
<div class="form-group">
    <?= $this->formLabel($power) ?>
    <?= $this->formElement($power) ?>
    <?= $this->formElementErrors()->render($power, ['class' => 'help-block']) ?>
</div>
    
<div class="form-group">
    <?= $this->formLabel($release_date) ?>
    <?= $this->formElement($release_date) ?>
    <?= $this->formElementErrors()->render($release_date, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($property) ?>
    <?= $this->formElement($property) ?>
    <?= $this->formElementErrors()->render($property, ['class' => 'help-block']) ?>
</div>
    
<div class="form-group">
    <?= $this->formLabel($description) ?>
    <?= $this->formElement($description) ?>
    <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
</div>
</fieldset>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($fieldset->get('id'));
echo $this->form()->closeTag();