<h3>Каталог товаров</h3>

<div class="list-group">
<?php
	$arr = $devices->toArray();
	$categories = [];
	foreach ($arr as $device){ 
		$category = $device['category']; 
		if(! in_array($category, $categories)){
			array_push($categories, $category)?>
			<details>
				<summary><?= $device['category']?></summary>
				<?php	foreach ($arr as $device){  
							if($device['category'] == $category){ ?>
								<a href="<?= $this->url('admin/detail', ['id' => $device['id']]) ?>">
									<?= $device['model'] ?><br/>
								</a>
							<?php	} ?>
				<?php } ?>
			</details>
		<?php } ?>
<?php } ?>
</div>
	
<div class="btn-group" role="group" aria-label="Post actions">
	<br><br><a class="btn btn-primary" href="<?= $this->url('admin/add') ?>">Добавить прибор</a>
</div>
